---
title: "gather flye assembly statistics"
author: "Laura Dijkhuizen"
date: "21/03/2022"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gather stats in long table with bash
```{bash}
# set working dir
cd /stor/anabaena
#get fq dir and samples from the main script.sh
fqdir=$(grep 'fqdir=' ./script.sh | cut -d '=' -f 2 | cut -d ' ' -f 1)
names=( $(find "$fqdir" -maxdepth 1 -name '*.fastq.gz' -printf '%P\n' | sed 's/.fastq.gz//g') )
echo "found sample names ${names[@]}"

# prep a table with headers
echo -e "samplename\tstatistic\tvalue" > denovo/flyestats.txt

# now gather stats in a table with a for loop
for   n in ${names[@]}
do    tail -n 8 ./denovo/$n/flye.log  \
      | head -n 6                     \
      | tr ' ' _                      \
      | tr -d ':'                     \
      | sed "s/^/$n/g"
done                                  \
| sed -E 's/ +/\t/g'                  \
>> denovo/flyestats.txt
```

## import flye stats in R
```{r}
setwd("/stor/anabaena")
library(data.table)
flye <- fread(file = "./denovo/flyestats.txt",header = T,colClasses = c('factor','factor','double'))
```

## convert lengths to mb
with some data.table magic
```{r}
bp_to_mb <- c('Fragments_N50','Largest_frg','Total_length')
flye[statistic %in% bp_to_mb,
     value := value/1000000
     ]
rm(bp_to_mb)
flye$value
```
## Make statistic a propper y axis label
```{r}
levels(flye$statistic) <- c("Fragments\n(count)",
                            "Fragments_N50\n(Mbase)",
                            "Largest_frg\n(Mbase)",
                            "Mean_coverage",
                            "Scaffolds",
                            "Total_length\n(Mbase)") 
```

## flye stats as (gg)plot
```{r}
library(ggplot2)
flyeplot <- ggplot(data = flye[statistic != 'Scaffolds:'],
                   mapping = aes(
                     x=samplename,
                     y=value,
                     fill=samplename
                     )) 
flyeplot <- flyeplot + geom_bar(stat = 'identity')
flyeplot <- flyeplot + facet_grid( statistic ~ .,scales = "free_y")
flyeplot <- flyeplot + theme_bw()
flyeplot <- flyeplot + theme(strip.text.y = element_text(angle=0))
flyeplot <- flyeplot + scale_fill_brewer(type = 'qual',
                                         palette = 2
                                         )
flyeplot
```




